# [Cocogitto](https://docs.cocogitto.io/) Configuration

from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = [ "main", "release/**", "gha-test-ci-**" ]
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []


[changelog]
path = "CHANGELOG.md"
authors = []


[commit_types]
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }
wip = { changelog_title = "Work In Progress", omit_from_changelog = true }


[bump_profiles]
